version: '3'

services:
  gui:
    container_name: gui
    build:
      context: ./gui
    ports:
      - "8501:8501"
    networks:
      - road_detection_network

  computer-vision:
    container_name: computer-vision
    build:
      context: ./computer-vision
    ports:
      - "8080:8080"
    networks:
      - road_detection_network

  stream:
    build:
      context: ./stream
    ports:
      - "8181:8181"
    networks:
     - road_detection_network
    
  triton-server:
    image: nvcr.io/nvidia/tritonserver:23.12-py3
    volumes:
      - ${PWD}/triton/model_repository:/models
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command:
      - tritonserver
      - --model-repository=/models
      - --backend-config=tensorflow,version=2
    networks:
      - road_detection_network
      
volumes:
  model_repository:

networks:
  road_detection_network:
    driver: bridge