apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: road-detection-hpa
  namespace: road-detection
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: road-detection-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
