apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-detection-gui-deployment
  namespace: road-detection
  labels:
    app: road-detection-gui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: road-detection-gui
  template:
    metadata:
      labels:
        app: road-detection-gui
    spec:
      containers:
      - name: road-detection-gui
        image: api.innovox.ai/road-detection-gui:v0.1.1
        imagePullPolicy: IfNotPresent
        env:
        # Define the environment variable
        - name: COMPUTER_VISION_GUI_PORT
          valueFrom:
            configMapKeyRef:
              name: road-detection-config
              key: COMPUTER_VISION_GUI_PORT
        - name: COMPUTER_VISION_SERVICE
          valueFrom:
            configMapKeyRef:
              name: road-detection-config
              key: COMPUTER_VISION_SERVICE
        - name: COMPUTER_VISION_PORT
          valueFrom:
            configMapKeyRef:
              name: road-detection-config
              key: COMPUTER_VISION_PORT     
      imagePullSecrets:
        - name: innovox-registry
---
apiVersion: v1
kind: Service
metadata:
  name: road-detection-gui-service
  namespace: road-detection
  labels:
    app: road-detection-gui-deployment
spec:
  selector:
    app: road-detection-gui
  ports:
    - name: road-detection-gui
      port: 80
      targetPort: 80
      nodePort: 30357
  type: NodePort