 apiVersion: monitoring.coreos.com/v1
 kind: PodMonitor
 metadata:
   name: kube-prometheus-stack-tritonmetrics
   namespace: road-detection
   labels:
       release: kube-prometheus-stack
 spec:
    selector:
       matchLabels:
          app: triton-server
    namespaceSelector:
       matchNames:
          - road-detection
    podMetricsEndpoints:
      - port: metrics-triton
        interval: 10s
        path: /metrics