# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\x12\x08requests\"\x1c\n\x0b\x46ileRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"h\n\x15TritonPredictResponse\x12\x16\n\x0e\x63lassification\x18\x01 \x01(\t\x12\x12\n\nframe_time\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t\"L\n\x14VideoPredictResponse\x12\x34\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1f.requests.TritonPredictResponse\"L\n\x14ImagePredictResponse\x12\x34\n\x0bpredictions\x18\x01 \x01(\x0b\x32\x1f.requests.TritonPredictResponse\"\\\n\x14ImageDataOCrResponse\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\t2Y\n\x14TritonPredictService\x12\x41\n\x07Predict\x12\x15.requests.FileRequest\x1a\x1f.requests.TritonPredictResponse2W\n\x13VideoPredictService\x12@\n\x07Predict\x12\x15.requests.FileRequest\x1a\x1e.requests.VideoPredictResponse2W\n\x13ImagePredictService\x12@\n\x07Predict\x12\x15.requests.FileRequest\x1a\x1e.requests.ImagePredictResponse2W\n\x13ImageDataOcrService\x12@\n\x07Predict\x12\x15.requests.FileRequest\x1a\x1e.requests.ImageDataOCrResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=28
  _globals['_FILEREQUEST']._serialized_end=56
  _globals['_TRITONPREDICTRESPONSE']._serialized_start=58
  _globals['_TRITONPREDICTRESPONSE']._serialized_end=162
  _globals['_VIDEOPREDICTRESPONSE']._serialized_start=164
  _globals['_VIDEOPREDICTRESPONSE']._serialized_end=240
  _globals['_IMAGEPREDICTRESPONSE']._serialized_start=242
  _globals['_IMAGEPREDICTRESPONSE']._serialized_end=318
  _globals['_IMAGEDATAOCRRESPONSE']._serialized_start=320
  _globals['_IMAGEDATAOCRRESPONSE']._serialized_end=412
  _globals['_TRITONPREDICTSERVICE']._serialized_start=414
  _globals['_TRITONPREDICTSERVICE']._serialized_end=503
  _globals['_VIDEOPREDICTSERVICE']._serialized_start=505
  _globals['_VIDEOPREDICTSERVICE']._serialized_end=592
  _globals['_IMAGEPREDICTSERVICE']._serialized_start=594
  _globals['_IMAGEPREDICTSERVICE']._serialized_end=681
  _globals['_IMAGEDATAOCRSERVICE']._serialized_start=683
  _globals['_IMAGEDATAOCRSERVICE']._serialized_end=770
# @@protoc_insertion_point(module_scope)
