# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_upload.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ile_upload.proto\"!\n\x11\x46ileUploadRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"=\n\x12\x46ileUploadResponse\x12\x16\n\x0e\x63lassification\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2H\n\x11\x46ileUploadService\x12\x33\n\x08SendFile\x12\x12.FileUploadRequest\x1a\x13.FileUploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_upload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=21
  _globals['_FILEUPLOADREQUEST']._serialized_end=54
  _globals['_FILEUPLOADRESPONSE']._serialized_start=56
  _globals['_FILEUPLOADRESPONSE']._serialized_end=117
  _globals['_FILEUPLOADSERVICE']._serialized_start=119
  _globals['_FILEUPLOADSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
